### ISSUE TITLE
 Uncaught (in promise) Error: [PADDLE] Unknown option parameter 'vendor'

### ISSUE THREAD

**Issue by pushkarsingh32** [team-gpt/paddle-billing-sdk#43]
`const PaymentPageClient = () => {
    const [yearly, setYearly] = useState(true);
    const [loading, setLoading] = useState({});
    const { session: supabaseSession } = useAuth();
    // const router = useRouter();
    // router.prefetch('/thank-you');

    const customerEmail = supabaseSession?.user?.email;
    const userId = supabaseSession?.user?.id;
    let [paddle, setPaddle] = useState(null);

    console.log("PaymentPageClient paddle: ", paddle);

    useEffect(() => {
        const clientSideToken = process.env.NEXT_PUBLIC_CLIENT_SIDE_TOKEN;
        loadScript().then((Paddle) => {
            Paddle.Environment.set("sandbox");
            Paddle.Setup({
                token: clientSideToken,
                vendor: process.env.NEXT_PUBLIC_PADDLE_SANDBOX_VENDOR_ID,
                checkout: {
                    settings: {
                        displayMode: "overlay",
                        theme: "light",
                        locale: "en",
                        allowLogout: false,
                        showAddDiscounts: false,
                    },
                },
                eventCallback: function (data) {
                    if (data?.name === "checkout.closed") {
                        setLoading({});
                    }
                }

            });
            setPaddle(Paddle);
            // // if paddle is null then setPaddle to Paddle
            // if (!paddle) {
            //     setPaddle(Paddle);
            // }
        });
    }, [setPaddle]);

    return (
        <div className=''>
            <PricingToggle yearly={yearly} setYearly={setYearly} />
            <PricingGrid yearly={yearly} paddle={paddle} customerEmail={customerEmail}
                userId={userId} loading={loading} setLoading={setLoading} />
        </div>
    )
}

export default PaymentPageClient;`

The code works fine when I first visit other pages on the app then come back to the payment page. 

however when I go to payment page first it doesn't load Paddle & gives error for vendor id paddle.js:1  Uncaught (in promise) Error: [PADDLE] Unknown option parameter 'vendor'
    at e.set (paddle.js:1:5676)
    at t.Setup (paddle.js:1:44889)
    
    in below line
`    return e.prototype.set = function(t) {
                if ("object" != typeof t)
                    throw new Error("[PADDLE] The Options() method accepts an object of options values.");
                for (var e in this.validateSeller(t.seller, t.token),
                t) {
                    if (!this.options.hasOwnProperty(e))
                        throw new Error("[PADDLE] Unknown option parameter '" + e + "'");
                    this.options[e] = t[e],
                    I.log("Set option '" + e + "' to '" + t[e] + "'.")
                }
            }`
            
  However on repeat visit it doesn't show any error. 
  
  Any idea on this why this behaviour is happening?

**Comment by kachar** [comment]
@pushkarsingh32 The problem you mentioned is caused by the React.js SDK running in the browser, not the Node SDK running on the server.

The error is about the usage of the deprecated `vendor` property in the SDK initialization. (Which btw might have to be `seller` and not `vendor`.
This property is now replaced by the usage of client-side tokens

- Read docs at https://developer.paddle.com/changelog/2023/client-side-tokens
- Issue new client-side token at https://vendors.paddle.com/authentication-v2
